<a href="https://colab.research.google.com/github/eleven111101/Decision_tree_ml/blob/main/Penguin_Species_DeT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
print("Heloo world")

Heloo world


In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [111]:
df=pd.read_csv("/content/penguins_size.csv")

In [112]:
df.shape

(344, 7)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [114]:
df.describe()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
count        342.000000       342.000000         342.000000   342.000000
mean          43.921930        17.151170         200.915205  4201.754386
std            5.459584         1.974793          14.061714   801.954536
min           32.100000        13.100000         172.000000  2700.000000
25%           39.225000        15.600000         190.000000  3550.000000
50%           44.450000        17.300000         197.000000  4050.000000
75%           48.500000        18.700000         213.000000  4750.000000
max           59.600000        21.500000         231.000000  6300.000000

In [115]:
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen              39.1             18.7              181.0   
1  Adelie  Torgersen              39.5             17.4              186.0   
2  Adelie  Torgersen              40.3             18.0              195.0   
3  Adelie  Torgersen               NaN              NaN                NaN   
4  Adelie  Torgersen              36.7             19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0       .  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [116]:
df.isnull().sum()

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [117]:
df.isnull().sum().sort_values(ascending=False)

sex                  10
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
species               0
island                0
dtype: int64

In [118]:
round(df.isnull().sum().sort_values(ascending=False) / len(df) *100,2)

sex                  2.91
culmen_length_mm     0.58
culmen_depth_mm      0.58
flipper_length_mm    0.58
body_mass_g          0.58
species              0.00
island               0.00
dtype: float64

In [119]:
df["sex"].unique()

array(['MALE', '.', 'FEMALE', nan], dtype=object)

In [120]:
from sklearn.impute import SimpleImputer

In [121]:
imputer = SimpleImputer(strategy = "most_frequent")

In [122]:
df.iloc[:,:] = imputer.fit_transform(df)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   culmen_length_mm   344 non-null    float64
 3   culmen_depth_mm    344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [124]:
df["species"].unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [125]:
df["island"].unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [126]:
dummies = pd.get_dummies(df["island"],prefix="IL_",drop_first=True)

In [127]:
df = pd.concat([dummies,df],axis=1)

In [128]:
df=df.drop("island",axis=1)

In [129]:
df.head(5)

IL__Dream  IL__Torgersen species  culmen_length_mm  culmen_depth_mm  \
0      False           True  Adelie              39.1             18.7   
1      False           True  Adelie              39.5             17.4   
2      False           True  Adelie              40.3             18.0   
3      False           True  Adelie              41.1             17.0   
4      False           True  Adelie              36.7             19.3   

   flipper_length_mm  body_mass_g     sex  
0              181.0       3750.0    MALE  
1              186.0       3800.0       .  
2              195.0       3250.0  FEMALE  
3              190.0       3800.0    MALE  
4              193.0       3450.0  FEMALE

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   IL__Dream          344 non-null    bool   
 1   IL__Torgersen      344 non-null    bool   
 2   species            344 non-null    object 
 3   culmen_length_mm   344 non-null    float64
 4   culmen_depth_mm    344 non-null    float64
 5   flipper_length_mm  344 non-null    float64
 6   body_mass_g        344 non-null    float64
 7   sex                344 non-null    object 
dtypes: bool(2), float64(4), object(2)
memory usage: 16.9+ KB


In [131]:
df["sex"].unique()

array(['MALE', '.', 'FEMALE'], dtype=object)

In [132]:
df["sex"]=="."

0      False
1       True
2      False
3      False
4      False
       ...  
339    False
340    False
341    False
342    False
343    False
Name: sex, Length: 344, dtype: bool

In [133]:
df[df["sex"]=="."]

IL__Dream  IL__Torgersen species  culmen_length_mm  culmen_depth_mm  \
1        False           True  Adelie              39.5             17.4   
336      False          False  Gentoo              44.5             15.7   

     flipper_length_mm  body_mass_g sex  
1                186.0       3800.0   .  
336              217.0       4875.0   .

In [134]:
len(df[df["sex"] == "."])


2

In [135]:
df = df[df["sex"] != "."]

In [136]:
df["sex"].unique()

array(['MALE', 'FEMALE'], dtype=object)

In [137]:
df["sex"]=df["sex"].apply(lambda x :1 if x=="MALE" else 0)

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 342 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   IL__Dream          342 non-null    bool   
 1   IL__Torgersen      342 non-null    bool   
 2   species            342 non-null    object 
 3   culmen_length_mm   342 non-null    float64
 4   culmen_depth_mm    342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                342 non-null    int64  
dtypes: bool(2), float64(4), int64(1), object(1)
memory usage: 19.4+ KB


In [140]:
X = df.drop("species",axis=1)
y = df["species"]

In [142]:
from sklearn.model_selection import train_test_split

In [143]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [144]:
from sklearn.tree import DecisionTreeClassifier

In [145]:
tree = DecisionTreeClassifier()

In [146]:
tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [148]:
prediction = tree.predict(X_test)

In [149]:
from sklearn.metrics import confusion_matrix ,  classification_report

In [151]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

      Adelie       1.00      0.94      0.97        35
   Chinstrap       0.86      1.00      0.92        12
      Gentoo       1.00      1.00      1.00        22

    accuracy                           0.97        69
   macro avg       0.95      0.98      0.96        69
weighted avg       0.98      0.97      0.97        69



In [152]:
print(confusion_matrix(y_test,prediction))

[[33  2  0]
 [ 0 12  0]
 [ 0  0 22]]
